from .primitives import Observation, Signal
from .enums import Category, Direction, Timeframe, SignalType
from .models import (
    StockPick,
    MacroIndicator,
    NewsItem,
    MarketSignal,
    Trend,
    Impact,
    Strength,
    Timeframe as ModelTimeframe,
    SignalType as ModelSignalType,
    to_json_dict,
    from_json_dict,
)
from .analysis_types import (
    StockMetrics,
    MacroContext,
    ConvictionScore,
    Risk,
    RiskCategory,
    ScoringConfig,
    Strategy,
    StrategyType,
)
from .analysis import (
    score_stock,
    classify_timeframe,
    identify_headwinds,
    identify_stock_risks,
    rank_picks,
    filter_by_strategy,
    generate_thesis,
)
from .scoring import (
    ScoredPick,
    ScoreFactor,
    ScoringThresholds,
    ScoringWeights,
    SectorSensitivities,
    TimeframeRules,
    score_stock as score_stock_v2,
    score_stocks,
    compute_valuation_score,
    compute_growth_score,
    compute_quality_score,
    compute_momentum_score,
    compute_analyst_score,
    compute_macro_adjustment,
    classify_timeframe as classify_timeframe_v2,
    generate_thesis as generate_thesis_v2,
    identify_risks,
    # Risk overlay
    RiskOverlayConfig,
    apply_risk_overlay,
    apply_risk_overlay_by_timeframe,
    FilteredPick,
    # Insider transactions
    InsiderTransaction,
    observations_to_insider_transactions,
)
from .news import (
    NewsCategory,
    NewsPriority,
    RawNewsItem,
    ScoredNewsItem,
    NewsAggregatorConfig,
    extract_tickers,
    score_source_credibility,
    score_recency,
    score_keywords,
    score_news_item,
    aggregate_news,
    deduplicate_news,
    filter_by_category,
    filter_by_ticker,
    filter_by_priority,
)
from .briefing import (
    EventImpact as BriefingEventImpact,
    EconomicEvent,
    PreMarketMover,
    EarningsAnnouncement,
    BriefingNewsItem,
    DailyBriefing,
    generate_daily_briefing,
    briefing_to_dict,
)
from .backtest import (
    BacktestConfig,
    BacktestTrade,
    BacktestResult,
    MonthlyReturn,
    TradeOutcome,
    run_backtest,
)
from .smart_money import (
    SmartMoneySignalType,
    TradeDirection,
    PoliticalParty,
    Chamber,
    OptionType,
    CongressTradeDetails,
    UnusualOptionsDetails,
    DarkPoolDetails,
    SmartMoneySignal,
    SmartMoneyContext,
    signal_to_dict,
    context_to_dict,
)

__all__ = [
    # Primitives (observation layer)
    "Observation",
    "Signal",
    # Enums (observation layer)
    "Category",
    "Direction",
    "Timeframe",
    "SignalType",
    # Domain models (analysis layer)
    "StockPick",
    "MacroIndicator",
    "NewsItem",
    "MarketSignal",
    "Trend",
    "Impact",
    "Strength",
    # Analysis types
    "StockMetrics",
    "MacroContext",
    "ConvictionScore",
    "Risk",
    "RiskCategory",
    "ScoringConfig",
    "Strategy",
    "StrategyType",
    # Analysis functions (legacy)
    "score_stock",
    "classify_timeframe",
    "identify_headwinds",
    "identify_stock_risks",
    "rank_picks",
    "filter_by_strategy",
    "generate_thesis",
    # Systematic scoring (v2)
    "ScoredPick",
    "ScoreFactor",
    "ScoringThresholds",
    "ScoringWeights",
    "SectorSensitivities",
    "TimeframeRules",
    "score_stock_v2",
    "score_stocks",
    "compute_valuation_score",
    "compute_growth_score",
    "compute_quality_score",
    "compute_momentum_score",
    "compute_analyst_score",
    "compute_macro_adjustment",
    "classify_timeframe_v2",
    "generate_thesis_v2",
    "identify_risks",
    # Insider transactions
    "InsiderTransaction",
    "observations_to_insider_transactions",
    # Risk overlay
    "RiskOverlayConfig",
    "apply_risk_overlay",
    "apply_risk_overlay_by_timeframe",
    "FilteredPick",
    # Serialization
    "to_json_dict",
    "from_json_dict",
    # News aggregation
    "NewsCategory",
    "NewsPriority",
    "RawNewsItem",
    "ScoredNewsItem",
    "NewsAggregatorConfig",
    "extract_tickers",
    "score_source_credibility",
    "score_recency",
    "score_keywords",
    "score_news_item",
    "aggregate_news",
    "deduplicate_news",
    "filter_by_category",
    "filter_by_ticker",
    "filter_by_priority",
    # Smart Money
    "SmartMoneySignalType",
    "TradeDirection",
    "PoliticalParty",
    "Chamber",
    "OptionType",
    "CongressTradeDetails",
    "UnusualOptionsDetails",
    "DarkPoolDetails",
    "SmartMoneySignal",
    "SmartMoneyContext",
    "signal_to_dict",
    "context_to_dict",
    # Briefing
    "BriefingEventImpact",
    "EconomicEvent",
    "PreMarketMover",
    "EarningsAnnouncement",
    "BriefingNewsItem",
    "DailyBriefing",
    "generate_daily_briefing",
    "briefing_to_dict",
    # Backtesting
    "BacktestConfig",
    "BacktestTrade",
    "BacktestResult",
    "MonthlyReturn",
    "TradeOutcome",
    "run_backtest",
]
