"""
Trading algorithm signal types for fintel.
Defines types for algorithm-generated trading signals, indicators, and configurations.
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum, auto
from typing import Any


class AlgorithmSignalType(Enum):
    """Type of trading signal generated by an algorithm."""

    LONG_ENTRY = auto()
    LONG_EXIT = auto()
    SHORT_ENTRY = auto()
    SHORT_EXIT = auto()
    STOP_LOSS = auto()
    TAKE_PROFIT = auto()
    NO_SIGNAL = auto()


@dataclass
class IndicatorSnapshot:
    """Snapshot of indicator values at signal time."""

    rsi: float | None = None
    macd_line: float | None = None
    macd_signal: float | None = None
    macd_histogram: float | None = None
    bb_upper: float | None = None
    bb_middle: float | None = None
    bb_lower: float | None = None
    atr: float | None = None
    sma_20: float | None = None
    sma_50: float | None = None
    sma_200: float | None = None
    ema_12: float | None = None
    ema_26: float | None = None
    volume_surge: bool = False
    volume_ratio: float | None = None


@dataclass
class AlgorithmSignal:
    """Trading signal generated by an algorithm."""

    ticker: str
    algorithm_id: str
    algorithm_name: str
    signal_type: AlgorithmSignalType
    confidence: float  # 0-1
    price_at_signal: float
    timestamp: datetime
    indicators: IndicatorSnapshot
    rationale: str
    suggested_entry: float | None = None
    suggested_stop: float | None = None
    suggested_target: float | None = None
    metadata: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if not 0.0 <= self.confidence <= 1.0:
            raise ValueError(f"confidence must be 0-1, got {self.confidence}")


@dataclass
class AlgorithmParameter:
    """Configuration parameter for an algorithm."""

    name: str
    param_type: str  # "int", "float", "bool"
    default: int | float | bool
    min_value: float | None = None
    max_value: float | None = None
    description: str = ""


@dataclass
class AlgorithmConfig:
    """Configuration for a trading algorithm."""

    algorithm_id: str
    name: str
    description: str
    version: str
    parameters: list[AlgorithmParameter] = field(default_factory=list)
